### PR TITLE
Support for documents (Doc_centre for User, Administrator and mangerial docs)

### PR DESCRIPTION
**Pull request by diwalipathak**
Changed:
* Reorganized documentation of the 5G-ERA Middleware to create ground for the constant documentation improvements

### CODE REVIEW

**Review by Artonus — CHANGES_REQUESTED** [review]
Changes to the documentation still need to be completed. The makeover was supposed to be made with the complete documentation, not only adding some new files.

**Comment by Artonus** [comment]
fixes #100

**Review by Artonus — APPROVED** [review]
Approved after the discussion, promised changes and improvements

**Review by diwalipathak — COMMENTED** [review]
docs: planning and replanning updates

**Review by diwalipathak — COMMENTED** [review]
docs : replanning doc update

**Pull request merged**
